"""
Cria o banco e popula com os dados dos tatuadores.

Rode uma vez: python seed_tatuadores.py
Pode rodar de novo sem medo — usa UPSERT pela coluna `classe`.
Substitua os valores de exemplo pelos dados reais.
"""

from database import Tatuador, criar_schema, salvar, listar_todos

TATUADORES = [
    Tatuador(
        classe="anabele",
        nome="Anabele Souza",
        apelido="Bel Ink",
        bio="Trabalha com fineline e traços delicados desde 2018.",
        especialidades="fineline, floral, minimalista",
        estudio="Estúdio Bel Ink",
        endereco="Av. T-4, 1234",
        bairro="Setor Bueno",
        cidade="Goiânia",
        estado="GO",
        cep="74230-035",
        latitude=-16.7024,
        longitude=-49.2712,
        telefone="+55 62 3000-0000",
        whatsapp="5562900000000",
        email="contato@belink.com.br",
        instagram="belink.tattoo",
        tiktok="belink.tattoo",
        site="https://belink.com.br",
        horario="Ter a Sáb, 10h às 19h",
        preco_medio="A partir de R$ 250",
    ),
    Tatuador(
        classe="chris",
        nome="Christian Lima",
        apelido="Chris",
        bio="Especialista em composições de alto contraste em blackwork e geometrias sagradas.",
        especialidades="blackwork, geométrico",
        estudio="Black House Tattoo",
        endereco="Rua 9, 500",
        bairro="Setor Oeste",
        cidade="Goiânia",
        estado="GO",
        cep="74110-100",
        latitude=-16.6799,
        longitude=-49.2654,
        telefone="+55 62 3000-0001",
        whatsapp="5562900000001",
        email="chris@blackhousetattoo.com.br",
        instagram="chris.blackwork",
        tiktok="chris.blackwork",
        site="https://blackhousetattoo.com.br",
        horario="Seg a Sex, 13h às 20h",
        preco_medio="A partir de R$ 350",
    ),
    Tatuador(
        classe="manuela",
        nome="Manuela Reis",
        apelido="Manu Reis",
        bio="Focada em aquarela e neotradicional com paletas vibrantes e autorais.",
        especialidades="aquarela, neotradicional, colorido",
        estudio="Artesania Tattoo Studio",
        endereco="Rua 136, 88",
        bairro="Setor Marista",
        cidade="Goiânia",
        estado="GO",
        cep="74180-040",
        latitude=-16.6975,
        longitude=-49.2581,
        telefone="+55 62 3000-0002",
        whatsapp="5562900000002",
        email="manu@artesaniatattoo.com.br",
        instagram="manu.reistattoo",
        tiktok="manu.reistattoo",
        site="https://artesaniatattoo.com.br",
        horario="Ter a Sáb, 11h às 19h",
        preco_medio="A partir de R$ 300",
    ),
    Tatuador(
        classe="matheus",
        nome="Matheus Andrade",
        apelido="Matheus Ink",
        bio="Artista focado em realismo em preto e cinza e retratos detalhados.",
        especialidades="realismo, preto e cinza, portrait",
        estudio="Legacy Tattoo Art",
        endereco="Av. Dep. Jamel Cecílio, 2900",
        bairro="Jardim Goiás",
        cidade="Goiânia",
        estado="GO",
        cep="74810-100",
        latitude=-16.7088,
        longitude=-49.2398,
        telefone="+55 62 3000-0003",
        whatsapp="5562900000003",
        email="matheus@legacytattoo.com.br",
        instagram="matheus.realism",
        tiktok="matheus.realism",
        site="https://legacytattoo.com.br",
        horario="Seg a Sáb, 10h às 18h",
        preco_medio="A partir de R$ 450",
    ),
    Tatuador(
        classe="michel",
        nome="Michel Ferreira",
        apelido="Michel OldSchool",
        bio="Referência em tatuagens estilo tradicional americano / Old School com linhas marcantes.",
        especialidades="old school, tradicional, bold line",
        estudio="Vintage Ink Club",
        endereco="Rua 3, 450",
        bairro="Setor Central",
        cidade="Goiânia",
        estado="GO",
        cep="74023-010",
        latitude=-16.6732,
        longitude=-49.2559,
        telefone="+55 62 3000-0004",
        whatsapp="5562900000004",
        email="michel@vintageink.com.br",
        instagram="michel.oldschool",
        tiktok="michel.oldschool",
        site="https://vintageink.com.br",
        horario="Ter a Sáb, 12h às 20h",
        preco_medio="A partir de R$ 200",
    ),
    Tatuador(
        classe="pablo",
        nome="Pablo Nunes",
        apelido="Pablo Oriental",
        bio="Especializado em tatuagens orientais de grande porte (Irezumi) e cultura oriental.",
        especialidades="oriental, irezumi, dragon",
        estudio="Ronin Tattoo Studio",
        endereco="Av. T-63, 1500",
        bairro="Setor Nova Suíça",
        cidade="Goiânia",
        estado="GO",
        cep="74280-110",
        latitude=-16.7112,
        longitude=-49.2680,
        telefone="+55 62 3000-0005",
        whatsapp="5562900000005",
        email="pablo@ronintattoo.com.br",
        instagram="pablo.irezumi",
        tiktok="pablo.irezumi",
        site="https://ronintattoo.com.br",
        horario="Seg a Sex, 10h às 18h",
        preco_medio="A partir de R$ 400",
    ),
]


if __name__ == "__main__":
    criar_schema()
    for t in TATUADORES:
        salvar(t)
    print(f"{len(TATUADORES)} tatuadores gravados.")
    for t in listar_todos():
        print(f"  - {t.classe}: {t.nome}")